// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT3ixqoRHaIVBSx6MWI2wyXSHFKO1xTlk',
    appId: '1:805402273722:web:71e3c9c97f88c7a1fd9f83',
    messagingSenderId: '805402273722',
    projectId: 'netplus-4a802',
    authDomain: 'netplus-4a802.firebaseapp.com',
    storageBucket: 'netplus-4a802.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApmtYuY1qbIDRvPQNf2bohoYKtB20mFlo',
    appId: '1:805402273722:android:ac7cb546a240b85dfd9f83',
    messagingSenderId: '805402273722',
    projectId: 'netplus-4a802',
    storageBucket: 'netplus-4a802.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnmo6clwBKct10au7pHrV-VnqpAr2tZcU',
    appId: '1:805402273722:ios:44ffe78711158f0ffd9f83',
    messagingSenderId: '805402273722',
    projectId: 'netplus-4a802',
    storageBucket: 'netplus-4a802.appspot.com',
    iosBundleId: 'com.example.netplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnmo6clwBKct10au7pHrV-VnqpAr2tZcU',
    appId: '1:805402273722:ios:8f6ab302b8eef8e7fd9f83',
    messagingSenderId: '805402273722',
    projectId: 'netplus-4a802',
    storageBucket: 'netplus-4a802.appspot.com',
    iosBundleId: 'com.example.netplus.RunnerTests',
  );
}
